select * from customer limit 20;


--total revenue generated by male vs customer

select gender,sum(purchase_amount) as revenue 
from customer 
group by gender;

--customer used discount but still spent more than the average purchase amount

select customer_id,purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) 
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

--compare average purchase amount between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2) 
from customer 
where shipping_type= 'Standard' or shipping_type = 'Express'
group by shipping_type;
-- having shipping_type= 'Standard' or shipping_type = 'Express';

--compare average sppend between and total revenue between subscribed and non-subscribed
select subscription_status,sum(purchase_amount) as total_revenue,
round(avg(purchase_amount),2) avg_spent ,
count(customer_id) as total_customers 
from customer 
group by subscription_status;


-- 5 products have highest percentage of purchases with discount applied
select item_purchased,  ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*),
           2
       ) AS discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

--segment customers into new returning and loyal based on their total
-- number of previous purchases and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 Then 'New'
	when previous_purchases between 2 and 10 Then 'Returning'
	Else 'loyal'
	End as customer_segment
from customer
)

select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;



-- what are the top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased, total_orders
from item_counts
where item_rank <= 3;


-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--What is the revenue contribution of each age group

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;










